version: '3.6'

services:
    db:
        image: mariadb
        restart: unless-stopped
        networks:
            kow: {}
        environment:
            MYSQL_ROOT_PASSWORD: "toor"
            MYSQL_DATABASE: "whois"
            MYSQL_USER: "whois"
            MYSQL_PASSWORD: "siohw"
        volumes:
            - ./db:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

    cache:
        image: redis
        restart: unless-stopped
        networks:
            kow: {}

    pma:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        environment:
            - PMA_HOST=db
        ports:
            - 127.0.0.1:8081:80
        networks:
            kow: {}
        depends_on:
            - db
            - cache

    api:
        image: kow/whois-api:latest
        build: kow-whois-api
        restart: unless-stopped
        networks:
            kow: {}
        ports:
            - 127.0.0.1:3000:5000
        depends_on:
            - db
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"

networks:
    kow:

